# Generated by Django 4.1.7 on 2023-03-28 11:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('test_pit', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': '测试项目', 'verbose_name_plural': '测试项目'},
        ),
        migrations.AddField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='项目描述'),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.BooleanField(default=True, verbose_name='状态'),
        ),
        migrations.AddField(
            model_name='project',
            name='type',
            field=models.IntegerField(choices=[(1, 'Web'), (2, 'App'), (3, '微服务')], default=1, verbose_name='产品类型'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='update_at',
            field=models.DateTimeField(auto_now=True, verbose_name='最近更新时间'),
        ),
        migrations.AddField(
            model_name='project',
            name='version',
            field=models.CharField(default='0.0.1', max_length=20, verbose_name='版本'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=200, verbose_name='测试项目名称'),
        ),
    ]
