# Generated by Django 4.1.7 on 2023-04-05 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('test_pit', '0002_alter_project_options_project_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjecMember',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('join_date', models.DateField(verbose_name='加入日期')),
                ('role', models.IntegerField(choices=[(1, '测试员'), (2, '测试组长'), (3, '测试经理'), (4, '开发'), (5, '运维'), (6, '项目经理')], verbose_name='角色')),
                ('status', models.BooleanField(default=True, verbose_name='状态')),
                ('quit_date', models.DateField(blank=True, null=True, verbose_name='退出日期')),
                ('memo', models.CharField(blank=True, max_length=200, null=True, verbose_name='备忘录')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='test_pit.project', verbose_name='测试项目')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '项目成员',
                'verbose_name_plural': '项目成员',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(related_name='project_members', through='test_pit.ProjecMember', to=settings.AUTH_USER_MODEL),
        ),
    ]
