# Generated by Django 4.1.7 on 2023-04-11 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_pit', '0003_projecmember_project_members'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeployEnv',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='环境名称')),
                ('hostname', models.CharField(help_text='主机名（IP）', max_length=50, verbose_name='主机名')),
                ('port', models.IntegerField(verbose_name='端口')),
                ('status', models.BooleanField(default=True, verbose_name='状态')),
                ('memo', models.CharField(blank=True, max_length=200, null=True, verbose_name='备忘录')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='test_pit.project', verbose_name='测试项目')),
            ],
            options={
                'verbose_name': '部署环境',
                'verbose_name_plural': '部署环境',
            },
        ),
    ]
